/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ProjectsPage = {
  _id: string;
  _type: "projectsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  description?: string;
  descriptionEn?: string;
  descriptionRu?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type FeaturedProjects = {
  _id: string;
  _type: "featuredProjects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  description?: string;
  descriptionEn?: string;
  descriptionRu?: string;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  briefDescription?: string;
  briefDescriptionEn?: string;
  briefDescriptionRu?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  fullDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  fullDescriptionEn?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  fullDescriptionRu?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type AnnouncementBanner = {
  _id: string;
  _type: "announcementBanner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  enabled?: boolean;
  badge?: string;
  badgeEn?: string;
  badgeRu?: string;
  message?: string;
  messageEn?: string;
  messageRu?: string;
  linkText?: string;
  linkTextEn?: string;
  linkTextRu?: string;
  linkUrl?: string;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  copyright?: string;
  copyrightEn?: string;
  copyrightRu?: string;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menuItems?: Array<{
    name?: string;
    nameEn?: string;
    nameRu?: string;
    link?: string;
    _key: string;
  }>;
};

export type ContactUs = {
  _id: string;
  _type: "contactUs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  description?: string;
  descriptionEn?: string;
  descriptionRu?: string;
  phone?: string;
  email?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type AboutUs = {
  _id: string;
  _type: "aboutUs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  subtitle?: string;
  subtitleEn?: string;
  subtitleRu?: string;
  description?: string;
  descriptionEn?: string;
  descriptionRu?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type ServicesSection = {
  _id: string;
  _type: "servicesSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  servicesTypes?: Array<{
    icon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    name?: string;
    nameEn?: string;
    nameRu?: string;
    description?: string;
    descriptionEn?: string;
    descriptionRu?: string;
    _key: string;
  }>;
};

export type HowWeWork = {
  _id: string;
  _type: "howWeWork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  subtitle?: string;
  subtitleEn?: string;
  subtitleRu?: string;
  steps?: Array<{
    stepDescription?: string;
    stepDescriptionEn?: string;
    stepDescriptionRu?: string;
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Hero = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  description?: string;
  descriptionEn?: string;
  descriptionRu?: string;
  buttonText?: string;
  buttonTextEn?: string;
  buttonTextRu?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ProjectsPage
  | SanityImageCrop
  | SanityImageHotspot
  | ProjectReference
  | FeaturedProjects
  | Project
  | AnnouncementBanner
  | Footer
  | Navigation
  | ContactUs
  | AboutUs
  | ServicesSection
  | HowWeWork
  | Hero
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/hooks/useSanityData.ts
// Variable: HERO_QUERY
// Query: *[_type == "hero" && _id == "hero"][0]
export type HERO_QUERY_RESULT = {
  _id: "hero";
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  description?: string;
  descriptionEn?: string;
  descriptionRu?: string;
  buttonText?: string;
  buttonTextEn?: string;
  buttonTextRu?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
} | null;

// Source: src/hooks/useSanityData.ts
// Variable: HOW_WE_WORK_QUERY
// Query: *[_type == "howWeWork" && _id == "howWeWork"][0]
export type HOW_WE_WORK_QUERY_RESULT = {
  _id: "howWeWork";
  _type: "howWeWork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  subtitle?: string;
  subtitleEn?: string;
  subtitleRu?: string;
  steps?: Array<{
    stepDescription?: string;
    stepDescriptionEn?: string;
    stepDescriptionRu?: string;
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
} | null;

// Source: src/hooks/useSanityData.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "servicesSection" && _id == "servicesSection"][0]
export type SERVICES_QUERY_RESULT = {
  _id: "servicesSection";
  _type: "servicesSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  servicesTypes?: Array<{
    icon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    name?: string;
    nameEn?: string;
    nameRu?: string;
    description?: string;
    descriptionEn?: string;
    descriptionRu?: string;
    _key: string;
  }>;
} | null;

// Source: src/hooks/useSanityData.ts
// Variable: ABOUT_US_QUERY
// Query: *[_type == "aboutUs" && _id == "aboutUs"][0]
export type ABOUT_US_QUERY_RESULT = {
  _id: "aboutUs";
  _type: "aboutUs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  subtitle?: string;
  subtitleEn?: string;
  subtitleRu?: string;
  description?: string;
  descriptionEn?: string;
  descriptionRu?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
} | null;

// Source: src/hooks/useSanityData.ts
// Variable: CONTACT_US_QUERY
// Query: *[_type == "contactUs" && _id == "contactUs"][0]
export type CONTACT_US_QUERY_RESULT = {
  _id: "contactUs";
  _type: "contactUs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  description?: string;
  descriptionEn?: string;
  descriptionRu?: string;
  phone?: string;
  email?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
} | null;

// Source: src/hooks/useSanityData.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation" && _id == "navigation"][0]
export type NAVIGATION_QUERY_RESULT = {
  _id: "navigation";
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menuItems?: Array<{
    name?: string;
    nameEn?: string;
    nameRu?: string;
    link?: string;
    _key: string;
  }>;
} | null;

// Source: src/hooks/useSanityData.ts
// Variable: FOOTER_QUERY
// Query: *[_type == "footer" && _id == "footer"][0]
export type FOOTER_QUERY_RESULT = {
  _id: "footer";
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  copyright?: string;
  copyrightEn?: string;
  copyrightRu?: string;
} | null;

// Source: src/hooks/useSanityData.ts
// Variable: ANNOUNCEMENT_BANNER_QUERY
// Query: *[_type == "announcementBanner" && _id == "announcementBanner"][0]
export type ANNOUNCEMENT_BANNER_QUERY_RESULT = {
  _id: "announcementBanner";
  _type: "announcementBanner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  enabled?: boolean;
  badge?: string;
  badgeEn?: string;
  badgeRu?: string;
  message?: string;
  messageEn?: string;
  messageRu?: string;
  linkText?: string;
  linkTextEn?: string;
  linkTextRu?: string;
  linkUrl?: string;
} | null;

// Source: src/hooks/useSanityData.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "featuredProjects" && _id == "featuredProjects"][0]{  ...,  projects[]->{    _id,    title,    titleEn,    titleRu,    briefDescription,    briefDescriptionEn,    briefDescriptionRu,    mainImage {      asset->{        url      }    }  }}
export type FEATURED_PROJECTS_QUERY_RESULT = {
  _id: "featuredProjects";
  _type: "featuredProjects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEn?: string;
  titleRu?: string;
  description?: string;
  descriptionEn?: string;
  descriptionRu?: string;
  projects: Array<{
    _id: string;
    title: string | null;
    titleEn: string | null;
    titleRu: string | null;
    briefDescription: string | null;
    briefDescriptionEn: string | null;
    briefDescriptionRu: string | null;
    mainImage: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  }> | null;
} | null;

// Source: src/hooks/useSanityData.ts
// Variable: PROJECTS_PAGE_QUERY
// Query: *[_type == "projectsPage" && _id == "projectsPage"][0]{  title,  titleEn,  titleRu,  description,  descriptionEn,  descriptionRu,  backgroundImage {    asset->{      url    }  }}
export type PROJECTS_PAGE_QUERY_RESULT = {
  title: string | null;
  titleEn: string | null;
  titleRu: string | null;
  description: string | null;
  descriptionEn: string | null;
  descriptionRu: string | null;
  backgroundImage: {
    asset: {
      url: string | null;
    } | null;
  } | null;
} | null;

// Source: src/hooks/useSanityData.ts
// Variable: ALL_PROJECTS_QUERY
// Query: *[_type == "project"] | order(_createdAt desc){  _id,  title,  titleEn,  titleRu,  briefDescription,  briefDescriptionEn,  briefDescriptionRu,  mainImage {    asset->{      url    }  }}
export type ALL_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  titleEn: string | null;
  titleRu: string | null;
  briefDescription: string | null;
  briefDescriptionEn: string | null;
  briefDescriptionRu: string | null;
  mainImage: {
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;

// Source: src/hooks/useSanityData.ts
// Variable: PROJECT_BY_ID_QUERY
// Query: *[_type == "project" && _id == $id][0]{  _id,  title,  titleEn,  titleRu,  briefDescription,  briefDescriptionEn,  briefDescriptionRu,  fullDescription,  fullDescriptionEn,  fullDescriptionRu,  mainImage {    asset->{      url    }  },  images[] {    asset->{      url    }  }}
export type PROJECT_BY_ID_QUERY_RESULT = {
  _id: string;
  title: string | null;
  titleEn: string | null;
  titleRu: string | null;
  briefDescription: string | null;
  briefDescriptionEn: string | null;
  briefDescriptionRu: string | null;
  fullDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  fullDescriptionEn: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  fullDescriptionRu: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  mainImage: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  images: Array<{
    asset: {
      url: string | null;
    } | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "hero" && _id == "hero"][0]': HERO_QUERY_RESULT;
    '*[_type == "howWeWork" && _id == "howWeWork"][0]': HOW_WE_WORK_QUERY_RESULT;
    '*[_type == "servicesSection" && _id == "servicesSection"][0]': SERVICES_QUERY_RESULT;
    '*[_type == "aboutUs" && _id == "aboutUs"][0]': ABOUT_US_QUERY_RESULT;
    '*[_type == "contactUs" && _id == "contactUs"][0]': CONTACT_US_QUERY_RESULT;
    '*[_type == "navigation" && _id == "navigation"][0]': NAVIGATION_QUERY_RESULT;
    '*[_type == "footer" && _id == "footer"][0]': FOOTER_QUERY_RESULT;
    '*[_type == "announcementBanner" && _id == "announcementBanner"][0]': ANNOUNCEMENT_BANNER_QUERY_RESULT;
    '*[_type == "featuredProjects" && _id == "featuredProjects"][0]{\n  ...,\n  projects[]->{\n    _id,\n    title,\n    titleEn,\n    titleRu,\n    briefDescription,\n    briefDescriptionEn,\n    briefDescriptionRu,\n    mainImage {\n      asset->{\n        url\n      }\n    }\n  }\n}': FEATURED_PROJECTS_QUERY_RESULT;
    '*[_type == "projectsPage" && _id == "projectsPage"][0]{\n  title,\n  titleEn,\n  titleRu,\n  description,\n  descriptionEn,\n  descriptionRu,\n  backgroundImage {\n    asset->{\n      url\n    }\n  }\n}': PROJECTS_PAGE_QUERY_RESULT;
    '*[_type == "project"] | order(_createdAt desc){\n  _id,\n  title,\n  titleEn,\n  titleRu,\n  briefDescription,\n  briefDescriptionEn,\n  briefDescriptionRu,\n  mainImage {\n    asset->{\n      url\n    }\n  }\n}': ALL_PROJECTS_QUERY_RESULT;
    '*[_type == "project" && _id == $id][0]{\n  _id,\n  title,\n  titleEn,\n  titleRu,\n  briefDescription,\n  briefDescriptionEn,\n  briefDescriptionRu,\n  fullDescription,\n  fullDescriptionEn,\n  fullDescriptionRu,\n  mainImage {\n    asset->{\n      url\n    }\n  },\n  images[] {\n    asset->{\n      url\n    }\n  }\n}': PROJECT_BY_ID_QUERY_RESULT;
  }
}
