/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ServicesSection = {
  _id: string;
  _type: "servicesSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  servicesTypes?: Array<{
    icon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    name?: string;
    description?: string;
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type HowWeWork = {
  _id: string;
  _type: "howWeWork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  steps?: Array<{
    stepDescription?: string;
    _key: string;
  }>;
};

export type Hero = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  buttonText?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ServicesSection
  | SanityImageCrop
  | SanityImageHotspot
  | HowWeWork
  | Hero
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/hooks/useSanityData.ts
// Variable: HERO_QUERY
// Query: *[_type == "hero"][0]
export type HERO_QUERY_RESULT = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  buttonText?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
} | null;

// Source: src/hooks/useSanityData.ts
// Variable: HOW_WE_WORK_QUERY
// Query: *[_type == "howWeWork"][0]
export type HOW_WE_WORK_QUERY_RESULT = {
  _id: string;
  _type: "howWeWork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  steps?: Array<{
    stepDescription?: string;
    _key: string;
  }>;
} | null;

// Source: src/hooks/useSanityData.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "servicesSection"][0]
export type SERVICES_QUERY_RESULT = {
  _id: string;
  _type: "servicesSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  servicesTypes?: Array<{
    icon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    name?: string;
    description?: string;
    _key: string;
  }>;
} | null;

// Source: src/hooks/useSanityData.ts
// Variable: ABOUT_US_QUERY
// Query: *[_type == "aboutUs"][0]
export type ABOUT_US_QUERY_RESULT = null;

// Source: src/hooks/useSanityData.ts
// Variable: CONTACT_US_QUERY
// Query: *[_type == "contactUs"][0]
export type CONTACT_US_QUERY_RESULT = null;

// Source: src/hooks/useSanityData.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation"][0]
export type NAVIGATION_QUERY_RESULT = null;

// Source: src/hooks/useSanityData.ts
// Variable: FOOTER_QUERY
// Query: *[_type == "footer"][0]
export type FOOTER_QUERY_RESULT = null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "hero"][0]': HERO_QUERY_RESULT;
    '*[_type == "howWeWork"][0]': HOW_WE_WORK_QUERY_RESULT;
    '*[_type == "servicesSection"][0]': SERVICES_QUERY_RESULT;
    '*[_type == "aboutUs"][0]': ABOUT_US_QUERY_RESULT;
    '*[_type == "contactUs"][0]': CONTACT_US_QUERY_RESULT;
    '*[_type == "navigation"][0]': NAVIGATION_QUERY_RESULT;
    '*[_type == "footer"][0]': FOOTER_QUERY_RESULT;
  }
}
