name: Deploy to cPanel
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Deploy build code
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp.mybld.bg
          username: ivo.tsochev@mybld.bg
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./dist/
