name: Deploy to cPanel
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: |
          npm install -g npm@11
          npm ci
      - name: Build code
        run: npm run build
      - name: Deploy build code
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp.mybld.bg
          username: ivo.tsochev@mybld.bg
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./dist/
          server-dir: public_html/
